server:
  port: 8080
spring:
  application:
    name: "nequi"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
traceconfig:
  type: "logback"
finacle:
  uri:
    freezeAccount: "/V1/banks/{bankId}/savings/FreezeAccount"
    unfreezeAccount: "/V1.0/banks/{bankId}/savings/accounts/{account}/freeze"

aws:
  accessKey: "******"
  secretKey: "******"

dynamodb:
  endpoint: http://localhost:4566/


web:
  client: https://a0f01868-b383-493a-974a-2bb4ef9d6a2b.mock.pstmn.io
  client2: https://a0f01868-b383-493a-974a-2bb4ef9d6a2b.mock.pstmn.io
